require("core.plugin_config.tokyonight")
require("core.plugin_config.vimdapui")
require("core.plugin_config.vimdap")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.neoscroll")
-- require("core.plugin_config.vimspector")

--require("core.plugin_config.nvim-treesitter")
require("core.plugin_config.commment")
