-- vim.g.vimspector_enable_mappings = 'HUMAN'
-- vim.keymap.set('n','<leader>da',"<cmd>call vimspector#Lauch() <Cr>")
-- vim.keymap.set('n','<leader>dx',"<cmd>call vimspector#Reset() <Cr>")
-- vim.keymap.set('n','<S-k>',"<cmd>call vimspector#StepOut() <Cr>")
-- vim.keymap.set('n','<S-l>',"<cmd>call vimspector#StepInto() <Cr>")
-- vim.keymap.set('n','<S-j>',"<cmd>call vimspector#StepOver() <Cr>")
-- vim.keymap.set('n','<leader>d_',"call vimspector#Restart()")
-- vim.keymap.set('n','<leader>dn',"call vimspector#Continue()")
-- vim.keymap.set('n','<leader>drc',"call vimspector#RunToCursor()")
-- vim.keymap.set('n','<leader>dh',"call vimspector#ToggleBreakPoint()")
-- vim.keymap.set('n','<leader>de',"call vimspector#ToggleConditionalBreakPoint()")
-- vim.keymap.set('n','<leader>de',"call vimspector#ClearBreakPoint()")
--
